# Use official Python image
FROM python:3.10-slim

# Copy our Python code from host to container
COPY ./Languages/python-runner.py /app/script.py
COPY ./Languages/input.txt /app/input.txt

# Set the working directory inside container
WORKDIR /app

# Run the script
CMD ["sh", "-c", "python script.py < input.txt"]
